export const MESSAGES_LOADING = 'MESSAGES_LOADING';
export const MESSAGES_LOADED = 'MESSAGES_LOADED';
export const MESSAGES_FAILED_TO_LOAD = 'MESSAGES_FAILED_TO_LOAD';

export const REQUEST_LOADED = 'REQUEST_LOADED';
export const REQUEST_LOADING = 'REQUEST_LOADING';
export const REQUEST_FAILED_TO_LOAD = 'REQUEST_FAILED_TO_LOAD';
